<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            // Europa
            ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€'],
            ['code' => 'GBP', 'name' => 'Sterlina Britannica', 'symbol' => '£'],
            ['code' => 'CHF', 'name' => 'Franco Svizzero', 'symbol' => 'CHF'],
            ['code' => 'SEK', 'name' => 'Corona Svedese', 'symbol' => 'kr'],
            ['code' => 'NOK', 'name' => 'Corona Norvegese', 'symbol' => 'kr'],
            ['code' => 'DKK', 'name' => 'Corona Danese', 'symbol' => 'kr'],
            ['code' => 'ISK', 'name' => 'Corona Islandese', 'symbol' => 'kr'],
            ['code' => 'PLN', 'name' => 'Zloty Polacco', 'symbol' => 'zł'],
            ['code' => 'CZK', 'name' => 'Corona Ceca', 'symbol' => 'Kč'],
            ['code' => 'HUF', 'name' => 'Fiorino Ungherese', 'symbol' => 'Ft'],
            ['code' => 'RON', 'name' => 'Leu Rumeno', 'symbol' => 'lei'],
            ['code' => 'BGN', 'name' => 'Lev Bulgaro', 'symbol' => 'лв'],
            ['code' => 'RSD', 'name' => 'Dinaro Serbo', 'symbol' => 'din'],
            ['code' => 'HRK', 'name' => 'Kuna Croata', 'symbol' => 'kn'],
            ['code' => 'BAM', 'name' => 'Marco Convertibile B-E', 'symbol' => 'KM'],
            ['code' => 'MKD', 'name' => 'Denar Macedone', 'symbol' => 'ден'],
            ['code' => 'ALL', 'name' => 'Lek Albanese', 'symbol' => 'L'],
            ['code' => 'MDL', 'name' => 'Leu Moldavo', 'symbol' => 'L'],
            ['code' => 'UAH', 'name' => 'Grivnia Ucraina', 'symbol' => '₴'],
            ['code' => 'BYN', 'name' => 'Rublo Bielorusso', 'symbol' => 'Br'],
            ['code' => 'RUB', 'name' => 'Rublo Russo', 'symbol' => '₽'],
            ['code' => 'GEL', 'name' => 'Lari Georgiano', 'symbol' => '₾'],
            ['code' => 'AMD', 'name' => 'Dram Armeno', 'symbol' => '֏'],
            ['code' => 'AZN', 'name' => 'Manat Azerbaigiano', 'symbol' => '₼'],
            ['code' => 'TRY', 'name' => 'Lira Turca', 'symbol' => '₺'],
            // Americhe
            ['code' => 'USD', 'name' => 'Dollaro USA', 'symbol' => '$'],
            ['code' => 'CAD', 'name' => 'Dollaro Canadese', 'symbol' => 'C$'],
            ['code' => 'MXN', 'name' => 'Peso Messicano', 'symbol' => '$'],
            ['code' => 'GTQ', 'name' => 'Quetzal Guatemalteco', 'symbol' => 'Q'],
            ['code' => 'BZD', 'name' => 'Dollaro del Belize', 'symbol' => 'BZ$'],
            ['code' => 'HNL', 'name' => 'Lempira Honduregno', 'symbol' => 'L'],
            ['code' => 'NIO', 'name' => 'Córdoba Nicaraguense', 'symbol' => 'C$'],
            ['code' => 'CRC', 'name' => 'Colón Costaricano', 'symbol' => '₡'],
            ['code' => 'PAB', 'name' => 'Balboa Panamense', 'symbol' => 'B/.'],
            ['code' => 'CUP', 'name' => 'Peso Cubano', 'symbol' => '$'],
            ['code' => 'DOP', 'name' => 'Peso Dominicano', 'symbol' => 'RD$'],
            ['code' => 'HTG', 'name' => 'Gourde Haitiano', 'symbol' => 'G'],
            ['code' => 'JMD', 'name' => 'Dollaro Giamaicano', 'symbol' => 'J$'],
            ['code' => 'TTD', 'name' => 'Dollaro di Trinidad e Tobago', 'symbol' => 'TT$'],
            ['code' => 'BBD', 'name' => 'Dollaro Barbadiano', 'symbol' => 'Bds$'],
            ['code' => 'XCD', 'name' => 'Dollaro dei Caraibi Orientali', 'symbol' => 'EC$'],
            ['code' => 'BSD', 'name' => 'Dollaro delle Bahamas', 'symbol' => 'B$'],
            ['code' => 'KYD', 'name' => 'Dollaro delle Isole Cayman', 'symbol' => 'CI$'],
            ['code' => 'AWG', 'name' => 'Fiorino di Aruba', 'symbol' => 'ƒ'],
            ['code' => 'ANG', 'name' => 'Fiorino delle Antille Olandesi', 'symbol' => 'ƒ'],
            ['code' => 'COP', 'name' => 'Peso Colombiano', 'symbol' => '$'],
            ['code' => 'VES', 'name' => 'Bolivar Venezuelano', 'symbol' => 'Bs.'],
            ['code' => 'GYD', 'name' => 'Dollaro della Guyana', 'symbol' => 'G$'],
            ['code' => 'SRD', 'name' => 'Dollaro del Suriname', 'symbol' => '$'],
            ['code' => 'BRL', 'name' => 'Real Brasiliano', 'symbol' => 'R$'],
            ['code' => 'PEN', 'name' => 'Sol Peruviano', 'symbol' => 'S/.'],
            ['code' => 'BOB', 'name' => 'Boliviano', 'symbol' => 'Bs'],
            ['code' => 'CLP', 'name' => 'Peso Cileno', 'symbol' => '$'],
            ['code' => 'ARS', 'name' => 'Peso Argentino', 'symbol' => '$'],
            ['code' => 'UYU', 'name' => 'Peso Uruguaiano', 'symbol' => '$U'],
            ['code' => 'PYG', 'name' => 'Guaraní Paraguaiano', 'symbol' => '₲'],
            ['code' => 'FKP', 'name' => 'Sterlina delle Falkland', 'symbol' => '£'],
            // Asia e Oceania
            ['code' => 'JPY', 'name' => 'Yen Giapponese', 'symbol' => '¥'],
            ['code' => 'CNY', 'name' => 'Yuan Cinese', 'symbol' => '¥'],
            ['code' => 'HKD', 'name' => 'Dollaro di Hong Kong', 'symbol' => 'HK$'],
            ['code' => 'TWD', 'name' => 'Nuovo Dollaro Taiwanese', 'symbol' => 'NT$'],
            ['code' => 'KRW', 'name' => 'Won Sudcoreano', 'symbol' => '₩'],
            ['code' => 'KPW', 'name' => 'Won Nordcoreano', 'symbol' => '₩'],
            ['code' => 'MNT', 'name' => 'Tugrik Mongolo', 'symbol' => '₮'],
            ['code' => 'INR', 'name' => 'Rupia Indiana', 'symbol' => '₹'],
            ['code' => 'PKR', 'name' => 'Rupia Pakistana', 'symbol' => '₨'],
            ['code' => 'BDT', 'name' => 'Taka Bangladese', 'symbol' => '৳'],
            ['code' => 'LKR', 'name' => 'Rupia dello Sri Lanka', 'symbol' => '₨'],
            ['code' => 'NPR', 'name' => 'Rupia Nepalese', 'symbol' => '₨'],
            ['code' => 'MVR', 'name' => 'Rufiyaa delle Maldive', 'symbol' => 'Rf'],
            ['code' => 'BTN', 'name' => 'Ngultrum Bhutanese', 'symbol' => 'Nu'],
            ['code' => 'MMK', 'name' => 'Kyat Birmano', 'symbol' => 'K'],
            ['code' => 'THB', 'name' => 'Baht Tailandese', 'symbol' => '฿'],
            ['code' => 'LAK', 'name' => 'Kip Laotiano', 'symbol' => '₭'],
            ['code' => 'KHR', 'name' => 'Riel Cambogiano', 'symbol' => '៛'],
            ['code' => 'VND', 'name' => 'Dong Vietnamita', 'symbol' => '₫'],
            ['code' => 'MYR', 'name' => 'Ringgit Malese', 'symbol' => 'RM'],
            ['code' => 'SGD', 'name' => 'Dollaro di Singapore', 'symbol' => 'S$'],
            ['code' => 'BND', 'name' => 'Dollaro del Brunei', 'symbol' => 'B$'],
            ['code' => 'IDR', 'name' => 'Rupia Indonesiana', 'symbol' => 'Rp'],
            ['code' => 'PHP', 'name' => 'Peso filippino', 'symbol' => '₱'],
            ['code' => 'KZT', 'name' => 'Tenge Kazako', 'symbol' => '₸'],
            ['code' => 'UZS', 'name' => 'Som Uzbeko', 'symbol' => 'лв'],
            ['code' => 'TMT', 'name' => 'Manat Turkmeno', 'symbol' => 'T'],
            ['code' => 'KGS', 'name' => 'Som Kirghiso', 'symbol' => 'лв'],
            ['code' => 'TJS', 'name' => 'Somoni Tagiko', 'symbol' => 'SM'],
            ['code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋'],
            ['code' => 'IRR', 'name' => 'Rial Iraniano', 'symbol' => '﷼'],
            ['code' => 'IQD', 'name' => 'Dinaro Iracheno', 'symbol' => 'ع.د'],
            ['code' => 'SYP', 'name' => 'Sterlina Siriana', 'symbol' => '£'],
            ['code' => 'LBP', 'name' => 'Sterlina Libanese', 'symbol' => 'ل.ل'],
            ['code' => 'JOD', 'name' => 'Dinaro Giordano', 'symbol' => 'د.ا'],
            ['code' => 'ILS', 'name' => 'Nuovo Shekel Israeliano', 'symbol' => '₪'],
            ['code' => 'SAR', 'name' => 'Riyal Saudita', 'symbol' => '﷼'],
            ['code' => 'AED', 'name' => 'Dirham degli Emirati', 'symbol' => 'د.إ'],
            ['code' => 'QAR', 'name' => 'Riyal del Qatar', 'symbol' => '﷼'],
            ['code' => 'KWD', 'name' => 'Dinaro Kuwaitiano', 'symbol' => 'د.ك'],
            ['code' => 'BHD', 'name' => 'Dinaro del Bahrain', 'symbol' => 'BD'],
            ['code' => 'OMR', 'name' => 'Rial dell\'Oman', 'symbol' => '﷼'],
            ['code' => 'YER', 'name' => 'Rial Yemenita', 'symbol' => '﷼'],
            ['code' => 'AUD', 'name' => 'Dollaro Australiano', 'symbol' => 'A$'],
            ['code' => 'NZD', 'name' => 'Dollaro Neozelandese', 'symbol' => 'NZ$'],
            ['code' => 'PGK', 'name' => 'Kina della Papua Nuova Guinea', 'symbol' => 'K'],
            ['code' => 'FJD', 'name' => 'Dollaro delle Fiji', 'symbol' => 'FJ$'],
            ['code' => 'SBD', 'name' => 'Dollaro delle Isole Salomone', 'symbol' => 'SI$'],
            ['code' => 'VUV', 'name' => 'Vatu di Vanuatu', 'symbol' => 'Vt'],
            ['code' => 'WST', 'name' => 'Tālā Samoano', 'symbol' => 'WS$'],
            ['code' => 'TOP', 'name' => 'Paʻanga Tongano', 'symbol' => 'T$'],
            ['code' => 'XPF', 'name' => 'Franco CFP', 'symbol' => 'Fr'],
            // Africa
            ['code' => 'ZAR', 'name' => 'Rand Sudafricano', 'symbol' => 'R'],
            ['code' => 'NGN', 'name' => 'Naira Nigeriana', 'symbol' => '₦'],
            ['code' => 'EGP', 'name' => 'Sterlina Egiziana', 'symbol' => '£'],
            ['code' => 'KES', 'name' => 'Scellino Keniota', 'symbol' => 'KSh'],
            ['code' => 'GHS', 'name' => 'Cedi Ghanese', 'symbol' => '₵'],
            ['code' => 'ETB', 'name' => 'Birr Etiope', 'symbol' => 'Br'],
            ['code' => 'TZS', 'name' => 'Scellino Tanzaniano', 'symbol' => 'TSh'],
            ['code' => 'UGX', 'name' => 'Scellino Ugandese', 'symbol' => 'USh'],
            ['code' => 'RWF', 'name' => 'Franco Ruandese', 'symbol' => 'Fr'],
            ['code' => 'MAD', 'name' => 'Dirham Marocchino', 'symbol' => 'MAD'],
            ['code' => 'TND', 'name' => 'Dinaro Tunisino', 'symbol' => 'د.ت'],
            ['code' => 'DZD', 'name' => 'Dinaro Algerino', 'symbol' => 'دج'],
            ['code' => 'LYD', 'name' => 'Dinaro Libico', 'symbol' => 'ل.د'],
            ['code' => 'SDG', 'name' => 'Sterlina Sudanese', 'symbol' => '£'],
            ['code' => 'MZN', 'name' => 'Metical Mozambicano', 'symbol' => 'MT'],
            ['code' => 'ZMW', 'name' => 'Kwacha Zambiano', 'symbol' => 'ZK'],
            ['code' => 'MWK', 'name' => 'Kwacha Malawiano', 'symbol' => 'MK'],
            ['code' => 'ZWL', 'name' => 'Dollaro dello Zimbabwe', 'symbol' => 'Z$'],
            ['code' => 'BWP', 'name' => 'Pula del Botswana', 'symbol' => 'P'],
            ['code' => 'NAD', 'name' => 'Dollaro Namibiano', 'symbol' => 'N$'],
            ['code' => 'SZL', 'name' => 'Lilangeni dello Swaziland', 'symbol' => 'L'],
            ['code' => 'LSL', 'name' => 'Loti del Lesotho', 'symbol' => 'L'],
            ['code' => 'AOA', 'name' => 'Kwanza Angolano', 'symbol' => 'Kz'],
            ['code' => 'CDF', 'name' => 'Franco Congolese', 'symbol' => 'Fr'],
            ['code' => 'XAF', 'name' => 'Franco CFA (Africa Centrale)', 'symbol' => 'Fr'],
            ['code' => 'XOF', 'name' => 'Franco CFA (Africa Occidentale)', 'symbol' => 'Fr'],
            ['code' => 'GNF', 'name' => 'Franco Guineano', 'symbol' => 'Fr'],
            ['code' => 'BIF', 'name' => 'Franco del Burundi', 'symbol' => 'Fr'],
            ['code' => 'DJF', 'name' => 'Franco di Gibuti', 'symbol' => 'Fr'],
            ['code' => 'KMF', 'name' => 'Franco delle Comore', 'symbol' => 'Fr'],
            ['code' => 'SOS', 'name' => 'Scellino Somalo', 'symbol' => 'Sh'],
            ['code' => 'ERN', 'name' => 'Nakfa Eritreo', 'symbol' => 'Nfk'],
            ['code' => 'MRU', 'name' => 'Ouguiya Mauritano', 'symbol' => 'UM'],
            ['code' => 'CVE', 'name' => 'Escudo di Capo Verde', 'symbol' => '$'],
            ['code' => 'STN', 'name' => 'Dobra di São Tomé e Príncipe', 'symbol' => 'Db'],
            ['code' => 'GMD', 'name' => 'Dalasi del Gambia', 'symbol' => 'D'],
            ['code' => 'SLL', 'name' => 'Leone della Sierra Leone', 'symbol' => 'Le'],
            ['code' => 'LRD', 'name' => 'Dollaro Liberiano', 'symbol' => 'L$'],
            ['code' => 'SLE', 'name' => 'Leone della Sierra Leone (nuovo)', 'symbol' => 'Le'],
            ['code' => 'MGA', 'name' => 'Ariary Malgascio', 'symbol' => 'Ar'],
            ['code' => 'SCR', 'name' => 'Rupia delle Seychelles', 'symbol' => '₨'],
            ['code' => 'MUR', 'name' => 'Rupia Mauriziana', 'symbol' => '₨'],
        ];

        foreach ($currencies as $currency) {
            Currency::updateOrCreate(
                ['code' => $currency['code']],
                $currency
            );
        }
    }
}
